### PR TITLE
Deletion Functionality Fix in GQL Resolver

### LINKED ISSUE #35: API Keys Format
Generate API keys, possibly as uuids

### PR DESCRIPTION
**Pull request by donjewey**
### Summary

Quick update to Resolvers to delete all associated projects and queries on deleteUser and all associated queries on deleteProject, making sure that database storage is freed up in every collection upon deletions of data in associated collections.

### Type of Change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)

### Evidence

-   Creating and Deleting were both tested in every respect, including in testing multiple deletions in every associated collection.

closes #35, #22

### CODE REVIEW

**Comment by donjewey** [comment]
Also just added API Key and endpoint generation to this PR.

API keys are random 10 character strings saved to each project entry in the DB.

Endpoints are structured as follows: `/:userID?project=[projectName]` 
User's project names must be unique, but different users can have the same project name.

File: server/schema/Resolvers.ts [hunk 1]
```diff
@@ -198,9 +214,8 @@ const resolvers: IResolvers = {
         ): Promise<ProjectQuery | Error> => {
```
Comment (shalarewicz) [inline server/schema/Resolvers.ts:214]: What's the business case for creating a query via the app? The way I've been thinking about it the app is just a visualization tool for queries that are already in the database and queries would be added to the database by the logging tool rather than through the UI? That being said this logic would definitely need to exist in the logging package

**Review by shalarewicz — COMMENTED** [review]
Good work but I think there's room to optimize some of the operations

File: server/models/Project.ts [hunk 2]
```diff
@@ -4,6 +4,8 @@ const projectSchema = new Schema({
     userID: { type: String, required: true },
     name: { type: String, required: true },
     queries: { type: Array, required: false },
+    endpoint: { type: String },
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/models/Project.ts:7]: this was something I forgot to remove, nice catch

File: server/schema/Helpers.ts [hunk 3]
```diff
@@ -0,0 +1,53 @@
+import QueryDB from '../models/Query';
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/schema/Helpers.ts:1]: yes

File: server/schema/Helpers.ts [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+import UserDB from '../models/User';
+
+// enter project query ID and deletes it from DB and associate project's queries array
+export function deleteQuery(id: string): Promise<ProjectQuery | Error> {
+    // also deletes projectID from userDB's project array
+    return QueryDB.findByIdAndRemove(id)
+        .then(async (query: ProjectQuery): Promise<ProjectQuery | Error> => {
+            // store project's query array to remove query to be deleted
+            const queryArr = await ProjectDB.findById(query.projectID).then(
+                (project: Project): Array<string> => project.queries
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/schema/Helpers.ts:12]: That's a much better idea

File: server/schema/Helpers.ts [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+        .catch((err: Error): Error => new Error(`DB query failed: ${err}`));
+}
+
+// enter project ID as parameter and deletes the project, all queries
+// associated, and the ID from associated user's project array
+export async function deleteProject(id: string): Promise<Project | Error> {
+    // first, goes through project's queries array and deletes each from DB
+    await ProjectDB.findById(id).then((project): void => {
+        for (let i = project.queries.length - 1; i >= 0; i -= 1) {
+            deleteQuery(project.queries[i]);
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/schema/Helpers.ts:32]: updated!

File: server/schema/Helpers.ts [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+        }
+    });
+
+    // also deletes projectID from userDB's project array
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/schema/Helpers.ts:36]: you made very convoluted solutions much more efficient. thank you

File: server/schema/Resolvers.ts [hunk 7]
```diff
@@ -81,6 +85,15 @@ const resolvers: IResolvers = {
         },
         deleteUser: async (parent: undefined, args: QueryByID): Promise<User | Error> => {
             const { id } = args;
+
+            // goes through project IDs array to delete each user project from DB
+            await UserDB.findById(id).then(async (user) => {
+                for (let i = user.projects.length - 1; i >= 0; i -= 1) {
+                    deleteProject(user.projects[i]);
```
[the remark this answers is not in the document]
Comment (donjewey) [reply server/schema/Resolvers.ts:91]: loops removed

File: server/schema/Resolvers.ts (hunk 1 above)
Comment (donjewey) [reply server/schema/Resolvers.ts:213]: This is the logic for the logger to add the queries to the app. The logger will be sending mutation requests to our apollo backend through axios/fetch

File: .eslintrc.json [hunk 8]
```diff
@@ -5,13 +5,14 @@
         "es2021": true
     },
     "extends": [
-        "react-app",
-        "eslint:recommended", 
-        "airbnb", 
-        "airbnb/hooks", 
-        "airbnb-typescript", 
+        "eslint:recommended",
+        "airbnb-base",
```
Comment (shalarewicz) [inline .eslintrc.json:9]: Why are we replacing `airbnb` with `airbnb-base`? The former includes support for react [docs](https://www.npmjs.com/package/eslint-config-airbnb)

File: client/components/Logger.tsx [hunk 9]
```diff
@@ -54,6 +54,7 @@ function Loger() {
             userId: '6286978e12716d47e6884194',
         },
     });
+    // eslint-disable-next-line no-console
```
Comment (shalarewicz) [inline client/components/Logger.tsx:57]: Let's leave the warnings in so that we know to come back and remove the console logs. These are just warnings so should be fine to leave in. If it's causing issues we can discuss

File: server/schema/Resolvers.ts (hunk 1 above)
Comment (shalarewicz) [reply server/schema/Resolvers.ts:196]: Can the logger and the app just use a shared database for queries? If I'm understanding what you're saying correctly the flow would look something like: 

- logger middleware intercepts query
- logger sends request to app server
- app server logs query in database
- app reads query from database and uses it in visualization

I think we can cut out a step and just do something like
- logger intercepts query
- logger records query in database
- app reads query info from database

File: .eslintrc.json (hunk 8 above)
Comment (donjewey) [reply .eslintrc.json:9]: will test out this change

File: @types/gql.d.ts [hunk 10]
```diff
@@ -51,25 +51,31 @@ type ProjectQuery = {
     name: string;
     depth: number;
     complexity: number;
-    time: number;
```
Comment (evanmcneely) [inline @types/gql.d.ts:54]: So we are removing `time` which I think is latency. Is the logger able to track latency? It could be a good metric to include.

File: server/index.ts [hunk 11]
```diff
@@ -26,11 +31,37 @@ app.use(cookieParser());
...
 // localhost:3000/gql -> graphQL sandbox
 server.start().then((): void => {
     server.applyMiddleware({ app, path: '/gql' });
-    app.listen(PORT, () => console.log(`[Server] Started on port :${PORT}`));
+
+    // routers
+    app.use('/api/users', userRouter);
+    app.use('/auth', authRouter);
+
+    // for testing purposes
```
Comment (evanmcneely) [inline server/index.ts:42]: Testing the logger?

File: server/index.ts [hunk 12]
```diff
@@ -54,7 +54,7 @@ server.start().then((): void => {
     });
 
     // serve homepage
-    app.use('/', (req, res) =>
+    app.all('/', (req, res) =>
```
Comment (shalarewicz) [inline server/index.ts:57]: What's the difference here between `all` and `use`?

File: server/models/Project.ts [hunk 13]
```diff
@@ -3,7 +3,8 @@ import mongoose, { Schema } from 'mongoose';
 const projectSchema = new Schema({
     userID: { type: String, required: true },
     name: { type: String, required: true },
-    queries: { type: Array, required: false },
```
Comment (evanmcneely) [inline server/models/Project.ts:6]: Projects aren't storing queries?

File: server/models/User.ts [hunk 14]
```diff
@@ -3,7 +3,6 @@ import mongoose, { Schema } from 'mongoose';
 const userSchema = new Schema({
     email: { type: String, required: true, unique: true },
     password: { type: String, required: true, unique: true },
-    projects: { type: Array, required: true },
```
Comment (evanmcneely) [inline server/models/User.ts:6]: Similar to above, shouldn't a user have a projects array? Maybe I'm missing something.

**Review by shalarewicz — APPROVED** [review]
Minor question. But seems good to me.

File: @types/gql.d.ts (hunk 10 above)
Comment (donjewey) [reply @types/gql.d.ts:54]: We have a timestamp property, are you thinking latency as well?

File: server/index.ts (hunk 11 above)
Comment (donjewey) [reply server/index.ts:42]: Yes!

File: server/index.ts (hunk 12 above)
Comment (donjewey) [reply server/index.ts:57]: This was because when it was `app.use()`, all requests to '/' were serving html. With `app.all()`, only the requests that reach the end of the middleware chain serve the html.

File: server/models/Project.ts (hunk 13 above)
Comment (donjewey) [reply server/models/Project.ts:6]: Queries are storing their associated project ID, and same with projects storing userIDs

File: server/models/User.ts (hunk 14 above)
Comment (donjewey) [reply server/models/User.ts:6]: Projects store their associated userID

File: @types/gql.d.ts (hunk 10 above)
Comment (evanmcneely) [reply @types/gql.d.ts:54]: Will create an issue for this.

**Review by evanmcneely — APPROVED** [review]
